import type { NetworkStructure } from './structure';
import { DEFAULT_DNS } from './dns';

const example: NetworkStructure = {
  version: 2,
  network: {
    dns: DEFAULT_DNS,
    subnet: '10.42.0',
    port: 51820,
    keepalive: 25,
    topology: 'hybrid',
    gatewayId: 'example-exit',
  },
  peers: [
    {
      id: 'example-exit',
      dns: null,
      name: 'exit-primary',
      label: 'Saída de internet padrão',
      lanIp: '',
      publicEndpointIp: '203.0.113.10',
      wgOctet: 1,
      role: 'hub',
      fullTunnel: false,
      gatewayId: '',
      natGateway: true,
      natInterface: 'ens3',
    },
    {
      id: 'example-alt',
      dns: null,
      name: 'exit-alternative',
      label: 'Saída alternativa do celular (sem failover automático)',
      lanIp: '',
      publicEndpointIp: '198.51.100.20',
      wgOctet: 2,
      role: 'hub',
      fullTunnel: false,
      gatewayId: '',
      natGateway: true,
      natInterface: 'eth0',
    },
    {
      id: 'example-services',
      dns: null,
      name: 'services-vps',
      label: 'Servidor de serviços, sem NAT',
      lanIp: '',
      publicEndpointIp: '192.0.2.30',
      wgOctet: 3,
      role: 'hub',
      fullTunnel: false,
      gatewayId: '',
      natGateway: false,
      natInterface: 'eth0',
    },
    {
      id: 'example-laptop',
      dns: null,
      name: 'laptop',
      label: 'Full Tunnel pela saída padrão',
      lanIp: '192.168.50.10',
      publicEndpointIp: '',
      wgOctet: 10,
      role: 'spoke',
      fullTunnel: true,
      gatewayId: '',
      natGateway: false,
      natInterface: 'eth0',
    },
    {
      id: 'example-phone',
      dns: null,
      name: 'phone',
      label: 'Cliente móvel com gateway próprio',
      lanIp: '',
      publicEndpointIp: '',
      wgOctet: 20,
      role: 'spoke',
      fullTunnel: true,
      gatewayId: 'example-alt',
      natGateway: false,
      natInterface: 'eth0',
    },
    {
      id: 'example-workstation',
      dns: null,
      name: 'workstation',
      label: 'Split Tunnel: só servidores pela VPN',
      lanIp: '192.168.50.30',
      publicEndpointIp: '',
      wgOctet: 30,
      role: 'spoke',
      fullTunnel: false,
      gatewayId: '',
      natGateway: false,
      natInterface: 'eth0',
    },
  ],
};

// Immutable, key-free input to the same validated import path used for user files.
export const EXAMPLE_STRUCTURE_JSON = JSON.stringify(example);
